### ISSUE TITLE
Voice activity/silence detection

### ISSUE THREAD

**Issue by kissze** [felipem1210/freetalkbot#18]
Hi,

it would be nice to implement a better/more accurate voice activity detection, like Silero. They have go package and it could be run on cpu or gpu also. I have tested the voice recognition with local whisper and its not slow if im using it on a nVidia GPU, but the silence detection is not so accurate. The "conversation" is a littlebit laggy.

https://github.com/streamer45/silero-vad-go
https://github.com/snakers4/silero-vad/blob/master/examples/go/cmd/main.go

ps: in the long run it would be also considerable to continue the voice detection, transcribing when the robot talking, because sometimes people needs to say, "no, i want something completely different".

Cheers,
Zoltan

**Comment by felipem1210** [comment]
Hey, that sounds great. Actually I implemented my own silence detection method because I didn't found any library for doing it. Thanks for sharing it, I will definitely give it a try. 

In the meanwhile have you tried playing with this variables?

```
silenceThreshold = 500             // Silence threshold
silenceDuration  = 3 * time.Second // Minimum duration of silence
```

The codec that asterisk choose is important! this threshold works well when codec is PCM 16bit linear 8khz. But for g711 I am pretty sure the silenceThreshold needs to be increased to minimum 1000 (If I remember good).

What you can do is to print the "volume" variable to see the values being  calculated. You can print it after 255:

`fmt.Printf("Volume: %v \n", volume)`

Let me know what you discover.

**Comment by kissze** [comment]
Actually thats why im googled a lot for VAD, because this onnx model based voice detection is a littlebit more complex, and maybe more accurate that checking the volume and the noise, because sometimes it is not enough.
I saw your parameters and tried some cases, and yepp, i figured it out that the "silence" is around 1000 in g711 and if we are talking, then the volume goes above 3000.

Anyway, the currently implemented silence detection is working, its not bad, but maybe it will be good to try with this more complex one.

The another thing is the continuity of the detection of speech, because i think the robot (tts) needs to be interruptable by the caller and real conversations more like duplex than the currently implemented question answer logic.

For example:

- Can you book me an apoointment for tomorrow?
- Yes, we have free slot in the morning, you can pick....... (and the robot will say some times, etc)
- No, i dont have time in the morning (says the caller even if the robot is talking)

I found an example but the guy not shared the code of their application, but the demo is impressing i think.
https://www.youtube.com/watch?v=kayBTMsQfto
You can see the demo from 11:30.

**Comment by felipem1210** [comment]
That's another level, will look at it.
