### ISSUE TITLE
Error getting audio payload

### ISSUE THREAD

**Issue by nilangablockstars** [felipem1210/freetalkbot#7]
Hi I created something like this for dailplan my local host via ngrok, 

`[from-internal-custom]

 exten = 500,1,Verbose("Call to AudioSocket via Dialplan Application")
 same = n,Answer()
 same = n,AudioSocket(40325ec2-5efd-4bd3-805f-53576e581d13,6.tcp.ngrok.io:15782)
 same = n,Hangup() `

but getting error as below

`error from audiosocket`

it happens this line
`case audiosocket.KindError:
			**log.Println("error from audiosocket")`
			
Could you tell me what is going on

**Comment by felipem1210** [comment]
Hi, thanks for raising the issue
This project is in a very initial phase and still can't be treated as a working project. Anyway I will try to help you.
If from the beginning you are receiving that message means that asterisk is not sending correct data to the audiosocket channel. I suggest checking the asterisk configuration and the audiosocket application implementation. 

https://docs.asterisk.org/Configuration/Channel-Drivers/AudioSocket/

**Comment by nilangablockstars** [comment]
Thank for the replay, I got the data like this
[output-0.wav.zip](https://github.com/user-attachments/files/16500516/output-0.wav.zip)

**Comment by felipem1210** [comment]
That is intended!!.
So far the audiosocket server is saving what you talk in a file, The idea is to convert it to text to then pass it to the chatbot. Checkout the architecture diagram. I will be working on it

**Comment by nilangablockstars** [comment]
I appreciate the help, but it seems that there may be data loss in the audio file, possibly due to missing frames or accelerated recording. Do you think this issue could be related to Asterisk not properly sending the correct audio chunks?

I'm still investigating why my Asterisk server isn't sending the correct audio data or if something else is missing.


also I wonder why we do not use ARI instead of audio socket!!

**Comment by felipem1210** [comment]
I see, yes, I experimented that as well, with the audiosocket voip server dockerized and asterisk as well, both in a docker network. 
Could be also networking latency that affects. Some audios that I get with my voice were with noise other were clean. That is something that will matter if the STT tool can't get what was talked. I will use Whisper. 

Regarding the usage of audiosocket instead of ARI, there is no strong technical reason behind it. I began this project inspired from this old implementation using audiosocket https://github.com/CyCoreSystems/audiosocket.
If you consider that ARI is a better candidate, could you explain it to me? I am interested about it.

**Comment by nilangablockstars** [comment]
Thanks! Good luck with your project. I will do more testing and try to figure out why my audio breaks. Also, I will do some testing with ARI and let you know.

**Comment by felipem1210** [comment]
@nilangablockstars to let you know. All the flow of the voip bot is completed. You can test it out!!. So far I haven't had any complication sending and receiving audio. What I am speaking is transcript correctly by whisper, and then I am hearing correctly the answer from the chatbot assistant. It detects the language with your first speak, so if you begin with a language, continue talking in it.
